name: Test the Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test the Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests
        uses: geode-sdk/build@v1

      - name: Combine results
        uses: geode-sdk/combine@v1
        with:
          files: results/**/*.json

